// tipo Number

const meuNumero = 3;

const primeiroNumero1 = 3;
const num2 = 2;

const operacaoMatematica = primeiroNumero1 + num2;

console.log(operacaoMatematica)

// ponto flutuante

const numeroPontoFlutuante = 3.3;

const pontoFlutuanteSemZero = .5;

const X = numeroPontoFlutuante + pontoFlutuanteSemZero;

console.log(X)  

//Nan -> Not A Number(não é um número)

const alura = "Alura";

console.log(alura * primeiroNumero1)

